---
networks:
  frontend:
    name: frontend
services:
  certbot-web:
    build: .
    ports:
      - 8086:8080
    volumes:
      - ./secrets/cloudflare.ini:/secrets/cloudflare.ini:ro
      - ./certbot-public:/public-certs
      - certbot-certs:/etc/letsencrypt
      - certbot-lib:/var/lib/letsencrypt
      - certbot-log:/var/log/letsencrypt
      - ./static:/app/static
    environment:
      - TZ=CEST
    networks:
      - frontend
    restart: unless-stopped

volumes:
  certbot-certs:
  certbot-lib:
  certbot-log: